### PR TITLE
Added very basic XPathFactoryPool to prevent a new factory being instant...

### PR DESCRIPTION
**Pull request by adamknightosl**
...iated for every xpath

### CODE REVIEW

**Comment by kaicode** [comment]
Thanks Adam. That looks like a brilliant enhancement.

Could I suggest a change to XPathFactoryPool to make it thread safe. It could be done without a synchronise block like so?

<pre>
public XPathFactory getInstance() {
    if(!pool.isEmpty()) {
        XPathFactory factory = pool.pop();
        // Thread safe check
        if (factory != null) {
            return factory;
        }
    }
    return XPathFactory.newInstance();
}
</pre>

Could I also suggest that you re-fork the master branch and reapply your changes in your repository, this pull request contains changes unrelated to the pooling feature and could be caused by your branch being out of date?

Thank you for your contribution to Rhinoforms, I look forward to merging your tweaked changes.

**Comment by johnpang28** [comment]
Hey, sorry for butting in...

Although synchronising the whole block is less efficient, it is actually safer than the single null check in multi-threaded environments.

It's actually a known issue that goes back many years, and not intuitive without some understanding of what happens under the bonnet of the jdk.

See: http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

**Comment by kaicode** [comment]
John

Thanks for the comment but I think that is only the case if using instance
variables, not local variables as is the case here?

We are not trying to create a singleton.

**Comment by adamknightosl** [comment]
Cheers guys, it's just like old times! :) I'll make a fresh fork. I did
merge the kaicode master into the opensquare fork to bring it up to date
before I made the change (at least I think I did, i'm still getting to
grips with git) but there might have been some other rubbish there. I'll
send through another pull request later on today.

On 4 December 2013 13:59, Kai Kewley notifications@github.com wrote:

> John
> 
> Thanks for the comment but I think that is only the case if using instance
> variables, not local variables as is the case here?
> 
> On 4 December 2013 13:51, John Pang notifications@github.com wrote:
> 
> > Hey, sorry for butting in...
> > 
> > Although synchronising the whole block is less efficient, it is actually
> > safer than the single null check in multi-threaded environments.
> > 
> > It's actually a known issue that goes back many years, and not intuitive
> > without some understanding of what happens under the bonnet of the jdk.
> > 
> > See:
> > http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/kaicode/rhinoforms/pull/32#issuecomment-29805792>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kaicode/rhinoforms/pull/32#issuecomment-29806290
> .

## 

_Adam Knight_

_Open Square_

+44 (0)1722 329 330

**Comment by johnpang28** [comment]
Kai

Just looked at the code again. Like you say, no harm done here. :)

**Comment by kaicode** [comment]
Thanks gentlemen

**Pull request closed without merging**
